version: 0.2
# env:
#   parameter-store:
#     key: "value"
#     key: "value"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing global packages
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
artifacts:
  files:
    - '**/*'